# Generated by Django 5.2.4 on 2025-07-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="url",
            field=models.CharField(blank=True, max_length=200, verbose_name="URL"),
        ),
    ]
